# Generated by Django 3.2.9 on 2022-08-08 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='auctions',
            new_name='products',
        ),
    ]
