# Generated by Django 3.2.9 on 2022-08-09 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_auctions_watchlist_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='closed',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='category_for_the_product', to='market.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='units_for_the_product', to='market.units'),
        ),
    ]
